package com.xinyirun.scm.core.system.mapper.business.order;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.xinyirun.scm.bean.entity.busniess.order.BOrderInvertedEntity;
import com.xinyirun.scm.bean.system.vo.business.order.BOrderInvertedExportVo;
import com.xinyirun.scm.bean.system.vo.business.order.BOrderInvertedVo;
import com.xinyirun.scm.common.constant.DictConstant;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * <p>
 *  Mapper 接口
 * </p>
 *
 * @author xinyirun
 * @since 2024-08-20
 */
@Repository
public interface BOrderInvertedMapper extends BaseMapper<BOrderInvertedEntity> {


    /**
     * 实时倒排查询
     */
    @Select(" SELECT * FROM(SELECT                                                                                                 "
            +"		CONCAT(substring( t1.contract_no, 6, 2 ), '-', substring( t1.contract_no, 8, 2 ),'-',                          "
            +"        substring( t1.contract_no, 10, 2 ),'-',t3.warehouse_id) AS export_code,                                      "
            +"		CONCAT(substring( t1.contract_no, 6, 2 ), '-', substring( t1.contract_no, 8, 2 ),'-',                          "
            +"        substring( t1.contract_no, 10, 2 )) AS auction_date,                                                         "
            +"		t3.audit_dt AS opening_date,                                                                                   "
            +"		t1.contract_no AS contract_no,                                                                                 "
            +"		DATE_ADD( t2.contract_expire_dt, INTERVAL - 7 DAY ) AS delivery_due_date,                                      "
            +"		t3.NAME AS warehouse_name,                                                                                     "
            +"		t1.contract_num AS contract_quantity,                                                                          "
            +"		IFNULL( t3.actual_count, 0 ) AS actual_quantity,                                                               "
            +"		IFNULL( t3.actual_count, 0 )- IFNULL( t5.actual_count, 0 ) AS remaining_quantity,                              "
            +"		IFNULL( t4.actual_count, 0 ) AS actual_daily_quantity,                                                         "
            +"		IFNULL( t5.actual_count, 0 ) AS accumulated_out_quantity,                                                      "
            +"		IF(DATEDIFF(DATE_ADD(t2.contract_expire_dt, INTERVAL - 7 DAY ),NOW()) <= 0,0,                                  "
            +"			IFNULL(DATEDIFF(DATE_ADD(t2.contract_expire_dt, INTERVAL - 7 DAY ),NOW()),0)) AS plan_out_days,            "
            +"		IF((IFNULL( t3.actual_count, 0 )- IFNULL( t5.actual_count, 0 )) <= 0.5,                                        "
            +"			ifnull(DATEDIFF( t5.e_dt, t3.audit_dt )+ 1,'-'),'-' ) AS actual_plan_out_days,                             "
            +"		CEIL(IF(DATEDIFF(DATE_ADD( t2.contract_expire_dt, INTERVAL - 7 DAY ),NOW()) <= 0,0,                            "
            +"			(IFNULL( t3.actual_count, 0 ) - IFNULL( t5.actual_count, 0 ))/ DATEDIFF(                                   "
            +"			DATE_ADD( t2.contract_expire_dt, INTERVAL - 7 DAY ),NOW()))) AS plan_out_day,                              "
            +"		IF(IFNULL( t3.actual_count, 0 ) < 1,0,(IFNULL( t5.actual_count, 0 )/ t3.actual_count) * 100) AS plan_out_speed "
            +"	FROM                                                                                                               "
            +"		b_order t1                                                                                                     "
            +"		LEFT JOIN b_in_order t2 ON t1.serial_id = t2.id                                                                "
            +"		AND t2.STATUS != '"+ DictConstant.DICT_B_IN_ORDER_STATUS_ONE+"'                                                 "
            +"		LEFT JOIN (                                                                                                    "
            +"		SELECT                                                                                                         "
            +"			tab2.order_id,                                                                                             "
            +"			tab4.id AS warehouse_id,                                                                                   "
            +"			tab4.NAME,                                                                                                 "
            +"			tab2.audit_dt,                                                                                             "
            +"			IFNULL( SUM( tab3.actual_count ), 0 ) AS actual_count                                                      "
            +"		FROM                                                                                                           "
            +"			b_in_plan tab1                                                                                             "
            +"			LEFT JOIN b_in_plan_detail tab2 ON tab2.plan_id = tab1.id                                                  "
            +"			LEFT JOIN b_in tab3 ON tab3.plan_detail_id = tab2.id                                                       "
            +"			LEFT JOIN m_warehouse tab4 ON tab4.id = tab2.warehouse_id                                                  "
            +"		WHERE                                                                                                          "
            +"		TRUE                                                                                                           "
            +"			AND tab1.type = '"+DictConstant.DICT_B_IN_PLAN_TYPE_CG+"'                                                  "
            +"			AND tab2.STATUS IN ('"+DictConstant.DICT_B_IN_PLAN_STATUS_TWO +"','"+DictConstant.DICT_B_IN_PLAN_STATUS_FIVE+"') "
            +"			AND tab3.STATUS = '"+DictConstant.DICT_B_IN_STATUS_TWO+"'                                               "
            +"			AND tab4.warehouse_type = '"+DictConstant.DICT_M_WAREHOUSE_TYPE_ZX+"'                                      "
            +"		GROUP BY                                                                                                       "
            +"			tab4.id,                                                                                                   "
            +"			tab2.order_id                                                                                              "
            +"		ORDER BY                                                                                                       "
            +"			tab2.audit_dt ASC                                                                                          "
            +"		) t3 ON t2.id = t3.order_id                                                                                    "
            +"		LEFT JOIN (                                                                                                    "
            +"		SELECT                                                                                                         "
            +"			SUM( tab4.actual_count ) AS actual_count,                                                                  "
            +"			tab4.warehouse_id,                                                                                         "
            +"			tab1.order_id                                                                                              "
            +"		FROM                                                                                                           "
            +"			b_schedule tab1                                                                                            "
            +"			LEFT JOIN b_monitor tab2 ON tab2.schedule_id = tab1.id                                                     "
            +"			LEFT JOIN b_monitor_out tab3 ON tab3.monitor_id = tab2.id                                                  "
            +"			LEFT JOIN b_out tab4 ON tab3.out_id = tab4.id                                                              "
            +"			LEFT JOIN m_warehouse tab5 ON tab5.id = tab4.warehouse_id                                                  "
            +"		WHERE                                                                                                          "
            +"		TRUE                                                                                                           "
            +"			AND tab5.warehouse_type = '"+DictConstant.DICT_M_WAREHOUSE_TYPE_ZX+"'                                      "
            +"			AND tab4.STATUS = '"+DictConstant.DICT_B_OUT_STATUS_PASSED+"'                                              "
            +"			AND tab2.STATUS IN ( '"+DictConstant.DICT_B_MONITOR_STATUS_THREE+"',                                       "
            +"                '"+DictConstant.DICT_B_MONITOR_STATUS_FOUR+"', '"+DictConstant.DICT_B_MONITOR_STATUS_FIVE+"',        "
            +"                '"+DictConstant.DICT_B_MONITOR_STATUS_SIX+"','"+DictConstant.DICT_B_MONITOR_STATUS_SEVEN+"' )        "
            +"			AND (date_format( tab4.e_dt, '%Y-%m-%d' ) = date_format(#{p1.date}, '%Y-%m-%d')  or  #{p1.date} is null)   "
            +"		GROUP BY                                                                                                       "
            +"			tab5.id,                                                                                                   "
            +"			tab1.order_id                                                                                              "
            +"		) t4 ON t4.order_id = t1.id                                                                                    "
            +"		LEFT JOIN (                                                                                                    "
            +"		SELECT                                                                                                         "
            +"			tab2.order_id,                                                                                             "
            +"			tab1.e_dt,                                                                                                 "
            +"			SUM( tab1.actual_count ) AS actual_count                                                                   "
            +"		FROM                                                                                                           "
            +"			b_out tab1                                                                                                 "
            +"			LEFT JOIN b_out_plan_detail tab2 ON tab2.id = tab1.plan_detail_id                                          "
            +"			LEFT JOIN b_out_plan tab3 ON tab3.id = tab2.plan_id                                                        "
            +"			LEFT JOIN m_warehouse tab4 ON tab4.id = tab1.warehouse_id                                                  "
            +"		WHERE                                                                                                          "
            +"		TRUE                                                                                                           "
            +"			AND tab3.type =  '"+DictConstant.DICT_B_OUT_PLAN_TYPE_JG+"'                                                "
            +"			AND tab2.STATUS =  '"+DictConstant.DICT_B_OUT_PLAN_STATUS_PASSED+"'                                        "
            +"			AND tab1.STATUS =  '"+DictConstant.DICT_B_OUT_STATUS_PASSED+"'                                             "
            +"			AND tab4.warehouse_type = '"+DictConstant.DICT_M_WAREHOUSE_TYPE_ZX+"'                                      "
            +"		GROUP BY                                                                                                       "
            +"			tab2.order_id                                                                                              "
            +"		ORDER BY                                                                                                       "
            +"			tab1.e_dt DESC                                                                                             "
            +"		) t5 ON t5.order_id = t2.id                                                                                    "
            +"	WHERE                                                                                                              "
            +"	TRUE                                                                                                               "
            +"		AND t1.serial_type = '"+DictConstant.DICT_SYS_CODE_TYPE_B_IN_ORDER+"'                                          "
            +"		AND t3.order_id IS NOT NULL                                                                                    "
            +"		AND t1.contract_no LIKE '%G0%'                                                                                 "
            +"	GROUP BY                                                                                                           "
            +"		t3.warehouse_id,                                                                                               "
            +"		t1.contract_no ) AS tab WHERE TRUE                                                                             "
            +"         AND (DATE_FORMAT(tab.opening_date,'%Y-%m-%d') >= DATE_FORMAT(#{p1.opening_date_start},'%Y-%m-%d') or #{p1.opening_date_start} is null  or #{p1.opening_date_start} ='')                "
            +"         AND (DATE_FORMAT(tab.opening_date,'%Y-%m-%d') <= DATE_FORMAT(#{p1.opening_date_end},'%Y-%m-%d') or #{p1.opening_date_end} is null or #{p1.opening_date_end} = '')                      "
            +"         AND ( tab.auction_date like CONCAT ('%',#{p1.auction_date,jdbcType=VARCHAR},'%') or #{p1.auction_date,jdbcType=VARCHAR} is null or #{p1.auction_date} = '')                            "
            +"         AND ( tab.actual_plan_out_days= #{p1.actual_plan_out_days,jdbcType=VARCHAR} or #{p1.actual_plan_out_days,jdbcType=VARCHAR} is null or #{p1.actual_plan_out_days,jdbcType=VARCHAR} ='') "
            +"         AND ( tab.plan_out_speed >= #{p1.plan_out_speed,jdbcType=VARCHAR} or #{p1.plan_out_speed,jdbcType=VARCHAR} is null or #{p1.plan_out_speed,jdbcType=VARCHAR} = '')                        "
    )
    List<BOrderInvertedVo> queryRealInvertedOrder(Page pageCondition,@Param("p1") BOrderInvertedVo searchCondition);

    /**
     * 日期组件查询
     */
    @Select(" SELECT date_format( t1.backups_date, '%Y-%m-%d' ) FROM b_order_inverted t1 GROUP BY t1.backups_date")
    List<String> getBadgeDate(BOrderInvertedVo searchCondition);

    /**
     * 实时倒排导出
     */
    @Select(" SELECT count(1) FROM(SELECT                                                                                                 "
            +"		CONCAT(substring( t1.contract_no, 6, 2 ), '-', substring( t1.contract_no, 8, 2 ),'-',                          "
            +"        substring( t1.contract_no, 10, 2 ),'-',t3.warehouse_id) AS export_code,                                      "
            +"		CONCAT(substring( t1.contract_no, 6, 2 ), '-', substring( t1.contract_no, 8, 2 ),'-',                          "
            +"        substring( t1.contract_no, 10, 2 )) AS auction_date,                                                         "
            +"		t3.audit_dt AS opening_date,                                                                                   "
            +"		t1.contract_no AS contract_no,                                                                                 "
            +"		DATE_ADD( t2.contract_expire_dt, INTERVAL - 7 DAY ) AS delivery_due_date,                                      "
            +"		t3.NAME AS warehouse_name,                                                                                     "
            +"		t1.contract_num AS contract_quantity,                                                                          "
            +"		IFNULL( t3.actual_count, 0 ) AS actual_quantity,                                                               "
            +"		IFNULL( t3.actual_count, 0 )- IFNULL( t5.actual_count, 0 ) AS remaining_quantity,                              "
            +"		IFNULL( t4.actual_count, 0 ) AS actual_daily_quantity,                                                         "
            +"		IFNULL( t5.actual_count, 0 ) AS accumulated_out_quantity,                                                      "
            +"		IF(DATEDIFF(DATE_ADD(t2.contract_expire_dt, INTERVAL - 7 DAY ),NOW()) <= 0,0,                                  "
            +"			IFNULL(DATEDIFF(DATE_ADD(t2.contract_expire_dt, INTERVAL - 7 DAY ),NOW()),0)) AS plan_out_days,            "
            +"		IF((IFNULL( t3.actual_count, 0 )- IFNULL( t5.actual_count, 0 )) <= 0.5,                                        "
            +"			ifnull(DATEDIFF( t5.e_dt, t3.audit_dt )+ 1,'-'),'-' ) AS actual_plan_out_days,                             "
            +"		CEIL(IF(DATEDIFF(DATE_ADD( t2.contract_expire_dt, INTERVAL - 7 DAY ),NOW()) <= 0,0,                            "
            +"			(IFNULL( t3.actual_count, 0 ) - IFNULL( t5.actual_count, 0 ))/ DATEDIFF(                                   "
            +"			DATE_ADD( t2.contract_expire_dt, INTERVAL - 7 DAY ),NOW()))) AS plan_out_day,                              "
            +"		IF(IFNULL( t3.actual_count, 0 ) < 1,0,(IFNULL( t5.actual_count, 0 )/ t3.actual_count) * 100) AS plan_out_speed "
            +"	FROM                                                                                                               "
            +"		b_order t1                                                                                                     "
            +"		LEFT JOIN b_in_order t2 ON t1.serial_id = t2.id                                                                "
            +"		AND t2.STATUS != '"+DictConstant.DICT_B_IN_ORDER_STATUS_ONE+"'                                                 "
            +"		LEFT JOIN (                                                                                                    "
            +"		SELECT                                                                                                         "
            +"			tab2.order_id,                                                                                             "
            +"			tab4.id AS warehouse_id,                                                                                   "
            +"			tab4.NAME,                                                                                                 "
            +"			tab2.audit_dt,                                                                                             "
            +"			IFNULL( SUM( tab3.actual_count ), 0 ) AS actual_count                                                      "
            +"		FROM                                                                                                           "
            +"			b_in_plan tab1                                                                                             "
            +"			LEFT JOIN b_in_plan_detail tab2 ON tab2.plan_id = tab1.id                                                  "
            +"			LEFT JOIN b_in tab3 ON tab3.plan_detail_id = tab2.id                                                       "
            +"			LEFT JOIN m_warehouse tab4 ON tab4.id = tab2.warehouse_id                                                  "
            +"		WHERE                                                                                                          "
            +"		TRUE                                                                                                           "
            +"			AND tab1.type = '"+DictConstant.DICT_B_IN_PLAN_TYPE_CG+"'                                                  "
            +"			AND tab2.STATUS IN ('"+DictConstant.DICT_B_IN_PLAN_STATUS_TWO +"','"+DictConstant.DICT_B_IN_PLAN_STATUS_FIVE+"') "
            +"			AND tab3.STATUS = '"+DictConstant.DICT_B_IN_STATUS_TWO+"'                                               "
            +"			AND tab4.warehouse_type = '"+DictConstant.DICT_M_WAREHOUSE_TYPE_ZX+"'                                      "
            +"		GROUP BY                                                                                                       "
            +"			tab4.id,                                                                                                   "
            +"			tab2.order_id                                                                                              "
            +"		ORDER BY                                                                                                       "
            +"			tab2.audit_dt ASC                                                                                          "
            +"		) t3 ON t2.id = t3.order_id                                                                                    "
            +"		LEFT JOIN (                                                                                                    "
            +"		SELECT                                                                                                         "
            +"			SUM( tab4.actual_count ) AS actual_count,                                                                  "
            +"			tab4.warehouse_id,                                                                                         "
            +"			tab1.order_id                                                                                              "
            +"		FROM                                                                                                           "
            +"			b_schedule tab1                                                                                            "
            +"			LEFT JOIN b_monitor tab2 ON tab2.schedule_id = tab1.id                                                     "
            +"			LEFT JOIN b_monitor_out tab3 ON tab3.monitor_id = tab2.id                                                  "
            +"			LEFT JOIN b_out tab4 ON tab3.out_id = tab4.id                                                              "
            +"			LEFT JOIN m_warehouse tab5 ON tab5.id = tab4.warehouse_id                                                  "
            +"		WHERE                                                                                                          "
            +"		TRUE                                                                                                           "
            +"			AND tab5.warehouse_type = '"+DictConstant.DICT_M_WAREHOUSE_TYPE_ZX+"'                                      "
            +"			AND tab4.STATUS = '"+DictConstant.DICT_B_OUT_STATUS_PASSED+"'                                              "
            +"			AND tab2.STATUS IN ( '"+DictConstant.DICT_B_MONITOR_STATUS_THREE+"',                                       "
            +"                '"+DictConstant.DICT_B_MONITOR_STATUS_FOUR+"', '"+DictConstant.DICT_B_MONITOR_STATUS_FIVE+"',        "
            +"                '"+DictConstant.DICT_B_MONITOR_STATUS_SIX+"','"+DictConstant.DICT_B_MONITOR_STATUS_SEVEN+"' )        "
            +"			AND (date_format( tab4.e_dt, '%Y-%m-%d' ) = date_format(#{p1.date}, '%Y-%m-%d')  or  #{p1.date} is null)   "
            +"			AND (date_format( tab4.e_dt, '%Y-%m-%d' ) = date_format(NOW(), '%Y-%m-%d')  or  #{p1.date} is not null)    "
            +"		GROUP BY                                                                                                       "
            +"			tab5.id,                                                                                                   "
            +"			tab1.order_id                                                                                              "
            +"		) t4 ON t4.order_id = t1.id                                                                                    "
            +"		LEFT JOIN (                                                                                                    "
            +"		SELECT                                                                                                         "
            +"			tab2.order_id,                                                                                             "
            +"			tab1.e_dt,                                                                                                 "
            +"			SUM( tab1.actual_count ) AS actual_count                                                                   "
            +"		FROM                                                                                                           "
            +"			b_out tab1                                                                                                 "
            +"			LEFT JOIN b_out_plan_detail tab2 ON tab2.id = tab1.plan_detail_id                                          "
            +"			LEFT JOIN b_out_plan tab3 ON tab3.id = tab2.plan_id                                                        "
            +"			LEFT JOIN m_warehouse tab4 ON tab4.id = tab1.warehouse_id                                                  "
            +"		WHERE                                                                                                          "
            +"		TRUE                                                                                                           "
            +"			AND tab3.type =  '"+DictConstant.DICT_B_OUT_PLAN_TYPE_JG+"'                                                "
            +"			AND tab2.STATUS =  '"+DictConstant.DICT_B_OUT_PLAN_STATUS_PASSED+"'                                        "
            +"			AND tab1.STATUS =  '"+DictConstant.DICT_B_OUT_STATUS_PASSED+"'                                             "
            +"			AND tab4.warehouse_type = '"+DictConstant.DICT_M_WAREHOUSE_TYPE_ZX+"'                                      "
            +"		GROUP BY                                                                                                       "
            +"			tab2.order_id                                                                                              "
            +"		ORDER BY                                                                                                       "
            +"			tab1.e_dt DESC                                                                                             "
            +"		) t5 ON t5.order_id = t2.id                                                                                    "
            +"	WHERE                                                                                                              "
            +"	TRUE                                                                                                               "
            +"		AND t1.serial_type = '"+DictConstant.DICT_SYS_CODE_TYPE_B_IN_ORDER+"'                                          "
            +"		AND t3.order_id IS NOT NULL                                                                                    "
            +"		AND t1.contract_no LIKE '%G0%') AS tab WHERE TRUE                                                                                    "
            +"         AND (DATE_FORMAT(tab.opening_date,'%Y-%m-%d') >= DATE_FORMAT(#{p1.opening_date_start},'%Y-%m-%d') or #{p1.opening_date_start} is null  or #{p1.opening_date_start} ='')                "
            +"         AND (DATE_FORMAT(tab.opening_date,'%Y-%m-%d') <= DATE_FORMAT(#{p1.opening_date_end},'%Y-%m-%d') or #{p1.opening_date_end} is null or #{p1.opening_date_end} = '')                      "
            +"         AND ( tab.auction_date like CONCAT ('%',#{p1.auction_date,jdbcType=VARCHAR},'%') or #{p1.auction_date,jdbcType=VARCHAR} is null or #{p1.auction_date} = '')                            "
            +"         AND ( tab.actual_plan_out_days= #{p1.actual_plan_out_days,jdbcType=VARCHAR} or #{p1.actual_plan_out_days,jdbcType=VARCHAR} is null or #{p1.actual_plan_out_days,jdbcType=VARCHAR} ='') "
            +"         AND ( tab.plan_out_speed= #{p1.plan_out_speed,jdbcType=VARCHAR} or #{p1.plan_out_speed,jdbcType=VARCHAR} is null or #{p1.plan_out_speed,jdbcType=VARCHAR} = '')                        "
//          +"	GROUP BY                                                                                                           "
//          +"		t3.warehouse_id,                                                                                               "
//          +"		t1.contract_no                                                                                                 "
    )
    int selectExportNum(@Param("p1") BOrderInvertedVo param);

    /**
     * 实时倒排导出
     */
    @Select(" SELECT * FROM(SELECT                                                                                                 "
            +"		@row_num:= @row_num+ 1 as no,                                                                                  "
            +"		CONCAT(substring( t1.contract_no, 6, 2 ), '-', substring( t1.contract_no, 8, 2 ),'-',                          "
            +"        substring( t1.contract_no, 10, 2 ),'-',t3.warehouse_id) AS export_code,                                      "
            +"		CONCAT(substring( t1.contract_no, 6, 2 ), '-', substring( t1.contract_no, 8, 2 ),'-',                          "
            +"        substring( t1.contract_no, 10, 2 )) AS auction_date,                                                         "
            +"		t3.audit_dt AS opening_date,                                                                                   "
            +"		t1.contract_no AS contract_no,                                                                                 "
            +"		DATE_ADD( t2.contract_expire_dt, INTERVAL - 7 DAY ) AS delivery_due_date,                                      "
            +"		t3.NAME AS warehouse_name,                                                                                     "
            +"		t1.contract_num AS contract_quantity,                                                                          "
            +"		IFNULL( t3.actual_count, 0 ) AS actual_quantity,                                                               "
            +"		IFNULL( t3.actual_count, 0 )- IFNULL( t5.actual_count, 0 ) AS remaining_quantity,                              "
            +"		IFNULL( t4.actual_count, 0 ) AS actual_daily_quantity,                                                         "
            +"		IFNULL( t5.actual_count, 0 ) AS accumulated_out_quantity,                                                      "
            +"		IF(DATEDIFF(DATE_ADD(t2.contract_expire_dt, INTERVAL - 7 DAY ),NOW()) <= 0,0,                                  "
            +"			IFNULL(DATEDIFF(DATE_ADD(t2.contract_expire_dt, INTERVAL - 7 DAY ),NOW()),0)) AS plan_out_days,            "
            +"		IF((IFNULL( t3.actual_count, 0 )- IFNULL( t5.actual_count, 0 )) <= 0.5,                                        "
            +"			ifnull(DATEDIFF( t5.e_dt, t3.audit_dt )+ 1,'-'),'-' ) AS actual_plan_out_days,                             "
            +"		CEIL(IF(DATEDIFF(DATE_ADD( t2.contract_expire_dt, INTERVAL - 7 DAY ),NOW()) <= 0,0,                             "
            +"			(IFNULL( t3.actual_count, 0 ) - IFNULL( t5.actual_count, 0 ))/ DATEDIFF(                                   "
            +"			DATE_ADD( t2.contract_expire_dt, INTERVAL - 7 DAY ),NOW()))) AS plan_out_day,                              "
            +"		IF(IFNULL( t3.actual_count, 0 ) < 1,0,(IFNULL( t5.actual_count, 0 )/ t3.actual_count) * 100) AS plan_out_speed "
            +"	FROM                                                                                                               "
            +"		b_order t1                                                                                                     "
            +"		LEFT JOIN b_in_order t2 ON t1.serial_id = t2.id                                                                "
            +"		AND t2.STATUS != '"+DictConstant.DICT_B_IN_ORDER_STATUS_ONE+"'                                                 "
            +"		LEFT JOIN (                                                                                                    "
            +"		SELECT                                                                                                         "
            +"			tab2.order_id,                                                                                             "
            +"			tab4.id AS warehouse_id,                                                                                   "
            +"			tab4.NAME,                                                                                                 "
            +"			tab2.audit_dt,                                                                                             "
            +"			IFNULL( SUM( tab3.actual_count ), 0 ) AS actual_count                                                      "
            +"		FROM                                                                                                           "
            +"			b_in_plan tab1                                                                                             "
            +"			LEFT JOIN b_in_plan_detail tab2 ON tab2.plan_id = tab1.id                                                  "
            +"			LEFT JOIN b_in tab3 ON tab3.plan_detail_id = tab2.id                                                       "
            +"			LEFT JOIN m_warehouse tab4 ON tab4.id = tab2.warehouse_id                                                  "
            +"		WHERE                                                                                                          "
            +"		TRUE                                                                                                           "
            +"			AND tab1.type = '"+DictConstant.DICT_B_IN_PLAN_TYPE_CG+"'                                                  "
            +"			AND tab2.STATUS IN ('"+DictConstant.DICT_B_IN_PLAN_STATUS_TWO +"','"+DictConstant.DICT_B_IN_PLAN_STATUS_FIVE+"') "
            +"			AND tab3.STATUS = '"+DictConstant.DICT_B_IN_STATUS_TWO+"'                                               "
            +"			AND tab4.warehouse_type = '"+DictConstant.DICT_M_WAREHOUSE_TYPE_ZX+"'                                      "
            +"		GROUP BY                                                                                                       "
            +"			tab4.id,                                                                                                   "
            +"			tab2.order_id                                                                                              "
            +"		ORDER BY                                                                                                       "
            +"			tab2.audit_dt ASC                                                                                          "
            +"		) t3 ON t2.id = t3.order_id                                                                                    "
            +"		LEFT JOIN (                                                                                                    "
            +"		SELECT                                                                                                         "
            +"			SUM( tab4.actual_count ) AS actual_count,                                                                  "
            +"			tab4.warehouse_id,                                                                                         "
            +"			tab1.order_id                                                                                              "
            +"		FROM                                                                                                           "
            +"			b_schedule tab1                                                                                            "
            +"			LEFT JOIN b_monitor tab2 ON tab2.schedule_id = tab1.id                                                     "
            +"			LEFT JOIN b_monitor_out tab3 ON tab3.monitor_id = tab2.id                                                  "
            +"			LEFT JOIN b_out tab4 ON tab3.out_id = tab4.id                                                              "
            +"			LEFT JOIN m_warehouse tab5 ON tab5.id = tab4.warehouse_id                                                  "
            +"		WHERE                                                                                                          "
            +"		TRUE                                                                                                           "
            +"			AND tab5.warehouse_type = '"+DictConstant.DICT_M_WAREHOUSE_TYPE_ZX+"'                                      "
            +"			AND tab4.STATUS = '"+DictConstant.DICT_B_OUT_STATUS_PASSED+"'                                              "
            +"			AND tab2.STATUS IN ( '"+DictConstant.DICT_B_MONITOR_STATUS_THREE+"',                                       "
            +"                '"+DictConstant.DICT_B_MONITOR_STATUS_FOUR+"', '"+DictConstant.DICT_B_MONITOR_STATUS_FIVE+"',        "
            +"                '"+DictConstant.DICT_B_MONITOR_STATUS_SIX+"','"+DictConstant.DICT_B_MONITOR_STATUS_SEVEN+"' )        "
            +"			AND (date_format( tab4.e_dt, '%Y-%m-%d' ) = date_format(#{p1.date}, '%Y-%m-%d')  or  #{p1.date} is null)   "
            +"			AND (date_format( tab4.e_dt, '%Y-%m-%d' ) = date_format(NOW(), '%Y-%m-%d')  or  #{p1.date} is not null)    "
            +"		GROUP BY                                                                                                       "
            +"			tab5.id,                                                                                                   "
            +"			tab1.order_id                                                                                              "
            +"		) t4 ON t4.order_id = t1.id                                                                                    "
            +"		LEFT JOIN (                                                                                                    "
            +"		SELECT                                                                                                         "
            +"			tab2.order_id,                                                                                             "
            +"			tab1.e_dt,                                                                                                 "
            +"			SUM( tab1.actual_count ) AS actual_count                                                                   "
            +"		FROM                                                                                                           "
            +"			b_out tab1                                                                                                 "
            +"			LEFT JOIN b_out_plan_detail tab2 ON tab2.id = tab1.plan_detail_id                                          "
            +"			LEFT JOIN b_out_plan tab3 ON tab3.id = tab2.plan_id                                                        "
            +"			LEFT JOIN m_warehouse tab4 ON tab4.id = tab1.warehouse_id                                                  "
            +"		WHERE                                                                                                          "
            +"		TRUE                                                                                                           "
            +"			AND tab3.type =  '"+DictConstant.DICT_B_OUT_PLAN_TYPE_JG+"'                                                "
            +"			AND tab2.STATUS =  '"+DictConstant.DICT_B_OUT_PLAN_STATUS_PASSED+"'                                        "
            +"			AND tab1.STATUS =  '"+DictConstant.DICT_B_OUT_STATUS_PASSED+"'                                             "
            +"			AND tab4.warehouse_type = '"+DictConstant.DICT_M_WAREHOUSE_TYPE_ZX+"'                                      "
            +"		GROUP BY                                                                                                       "
            +"			tab2.order_id                                                                                              "
            +"		ORDER BY                                                                                                       "
            +"			tab1.e_dt DESC                                                                                             "
            +"		) t5 ON t5.order_id = t2.id,(select @row_num:=0) t6                                                            "
            +"	WHERE                                                                                                              "
            +"	TRUE                                                                                                               "
            +"		AND t1.serial_type = '"+DictConstant.DICT_SYS_CODE_TYPE_B_IN_ORDER+"'                                          "
            +"		AND t3.order_id IS NOT NULL                                                                                    "
            +"		AND t1.contract_no LIKE '%G0%'                                                                                 "
            +"	GROUP BY                                                                                                           "
            +"		t3.warehouse_id,                                                                                               "
            +"		t1.contract_no ) AS tab WHERE TRUE                                                                                    "
            +"         AND (DATE_FORMAT(tab.opening_date,'%Y-%m-%d') >= DATE_FORMAT(#{p1.opening_date_start},'%Y-%m-%d') or #{p1.opening_date_start} is null  or #{p1.opening_date_start} ='')                "
            +"         AND (DATE_FORMAT(tab.opening_date,'%Y-%m-%d') <= DATE_FORMAT(#{p1.opening_date_end},'%Y-%m-%d') or #{p1.opening_date_end} is null or #{p1.opening_date_end} = '')                      "
            +"         AND ( tab.auction_date like CONCAT ('%',#{p1.auction_date,jdbcType=VARCHAR},'%') or #{p1.auction_date,jdbcType=VARCHAR} is null or #{p1.auction_date} = '')                            "
            +"         AND ( tab.actual_plan_out_days= #{p1.actual_plan_out_days,jdbcType=VARCHAR} or #{p1.actual_plan_out_days,jdbcType=VARCHAR} is null or #{p1.actual_plan_out_days,jdbcType=VARCHAR} ='') "
            +"         AND ( tab.plan_out_speed >= #{p1.plan_out_speed,jdbcType=VARCHAR} or #{p1.plan_out_speed,jdbcType=VARCHAR} is null or #{p1.plan_out_speed,jdbcType=VARCHAR} = '')                        "

    )
    List<BOrderInvertedExportVo> queryRealInvertedExportAll(@Param("p1") BOrderInvertedVo param);

    /**
     * 实时倒排导出
     */
    @Select(" <script> "
            +"	SELECT                                                                                                             "
            +"		@row_num:= @row_num+ 1 as no,                                                                                  "
            +"		CONCAT(substring( t1.contract_no, 6, 2 ), '-', substring( t1.contract_no, 8, 2 ),'-',                          "
            +"        substring( t1.contract_no, 10, 2 ),'-',t3.warehouse_id) AS export_code,                                      "
            +"		CONCAT(substring( t1.contract_no, 6, 2 ), '-', substring( t1.contract_no, 8, 2 ),'-',                          "
            +"        substring( t1.contract_no, 10, 2 )) AS auction_date,                                                         "
            +"		t3.audit_dt AS opening_date,                                                                                   "
            +"		t1.contract_no AS contract_no,                                                                                 "
            +"		DATE_ADD( t2.contract_expire_dt, INTERVAL - 7 DAY ) AS delivery_due_date,                                      "
            +"		t3.NAME AS warehouse_name,                                                                                     "
            +"		t1.contract_num AS contract_quantity,                                                                          "
            +"		IFNULL( t3.actual_count, 0 ) AS actual_quantity,                                                               "
            +"		IFNULL( t3.actual_count, 0 )- IFNULL( t5.actual_count, 0 ) AS remaining_quantity,                              "
            +"		IFNULL( t4.actual_count, 0 ) AS actual_daily_quantity,                                                         "
            +"		IFNULL( t5.actual_count, 0 ) AS accumulated_out_quantity,                                                      "
            +"		IF(DATEDIFF(DATE_ADD(t2.contract_expire_dt, INTERVAL - 7 DAY ),NOW()) &lt;= 0,0,                               "
            +"			IFNULL(DATEDIFF(DATE_ADD(t2.contract_expire_dt, INTERVAL - 7 DAY ),NOW()),0)) AS plan_out_days,            "
            +"		IF((IFNULL( t3.actual_count, 0 )- IFNULL( t5.actual_count, 0 )) &lt;= 0.5,                                     "
            +"			ifnull(DATEDIFF( t5.e_dt, t3.audit_dt )+ 1,'-'),'-' ) AS actual_plan_out_days,                             "
            +"		CEIL(IF(DATEDIFF(DATE_ADD( t2.contract_expire_dt, INTERVAL - 7 DAY ),NOW()) &lt;= 0,0,                         "
            +"			(IFNULL( t3.actual_count, 0 ) - IFNULL( t5.actual_count, 0 ))/ DATEDIFF(                                   "
            +"			DATE_ADD( t2.contract_expire_dt, INTERVAL - 7 DAY ),NOW()))) AS plan_out_day,                              "
            +"		IF(IFNULL( t3.actual_count, 0 ) &lt; 1,0,(IFNULL( t5.actual_count, 0 )/ t3.actual_count) * 100) AS plan_out_speed "
            +"	FROM                                                                                                               "
            +"		b_order t1                                                                                                     "
            +"		LEFT JOIN b_in_order t2 ON t1.serial_id = t2.id                                                                "
            +"		AND t2.STATUS != '"+DictConstant.DICT_B_IN_ORDER_STATUS_ONE+"'                                                 "
            +"		LEFT JOIN (                                                                                                    "
            +"		SELECT                                                                                                         "
            +"			tab2.order_id,                                                                                             "
            +"			tab4.id AS warehouse_id,                                                                                   "
            +"			tab4.NAME,                                                                                                 "
            +"			tab2.audit_dt,                                                                                             "
            +"			IFNULL( SUM( tab3.actual_count ), 0 ) AS actual_count                                                      "
            +"		FROM                                                                                                           "
            +"			b_in_plan tab1                                                                                             "
            +"			LEFT JOIN b_in_plan_detail tab2 ON tab2.plan_id = tab1.id                                                  "
            +"			LEFT JOIN b_in tab3 ON tab3.plan_detail_id = tab2.id                                                       "
            +"			LEFT JOIN m_warehouse tab4 ON tab4.id = tab2.warehouse_id                                                  "
            +"		WHERE                                                                                                          "
            +"		TRUE                                                                                                           "
            +"			AND tab1.type = '"+DictConstant.DICT_B_IN_PLAN_TYPE_CG+"'                                                  "
            +"			AND tab2.STATUS IN ('"+DictConstant.DICT_B_IN_PLAN_STATUS_TWO +"','"+DictConstant.DICT_B_IN_PLAN_STATUS_FIVE+"') "
            +"			AND tab3.STATUS = '"+DictConstant.DICT_B_IN_STATUS_TWO+"'                                               "
            +"			AND tab4.warehouse_type = '"+DictConstant.DICT_M_WAREHOUSE_TYPE_ZX+"'                                      "
            +"		GROUP BY                                                                                                       "
            +"			tab4.id,                                                                                                   "
            +"			tab2.order_id                                                                                              "
            +"		ORDER BY                                                                                                       "
            +"			tab2.audit_dt ASC                                                                                          "
            +"		) t3 ON t2.id = t3.order_id                                                                                    "
            +"		LEFT JOIN (                                                                                                    "
            +"		SELECT                                                                                                         "
            +"			SUM( tab4.actual_count ) AS actual_count,                                                                  "
            +"			tab4.warehouse_id,                                                                                         "
            +"			tab1.order_id                                                                                              "
            +"		FROM                                                                                                           "
            +"			b_schedule tab1                                                                                            "
            +"			LEFT JOIN b_monitor tab2 ON tab2.schedule_id = tab1.id                                                     "
            +"			LEFT JOIN b_monitor_out tab3 ON tab3.monitor_id = tab2.id                                                  "
            +"			LEFT JOIN b_out tab4 ON tab3.out_id = tab4.id                                                              "
            +"			LEFT JOIN m_warehouse tab5 ON tab5.id = tab4.warehouse_id                                                  "
            +"		WHERE                                                                                                          "
            +"		TRUE                                                                                                           "
            +"			AND tab5.warehouse_type = '"+DictConstant.DICT_M_WAREHOUSE_TYPE_ZX+"'                                      "
            +"			AND tab4.STATUS = '"+DictConstant.DICT_B_OUT_STATUS_PASSED+"'                                              "
            +"			AND tab2.STATUS IN ( '"+DictConstant.DICT_B_MONITOR_STATUS_THREE+"',                                       "
            +"                '"+DictConstant.DICT_B_MONITOR_STATUS_FOUR+"', '"+DictConstant.DICT_B_MONITOR_STATUS_FIVE+"',        "
            +"                '"+DictConstant.DICT_B_MONITOR_STATUS_SIX+"','"+DictConstant.DICT_B_MONITOR_STATUS_SEVEN+"' )        "
            +"			AND (date_format( tab4.e_dt, '%Y-%m-%d' ) = date_format(#{p1.date}, '%Y-%m-%d')  or  #{p1.date} is null)   "
            +"		GROUP BY                                                                                                       "
            +"			tab5.id,                                                                                                   "
            +"			tab1.order_id                                                                                              "
            +"		) t4 ON t4.order_id = t1.id                                                                                    "
            +"		LEFT JOIN (                                                                                                    "
            +"		SELECT                                                                                                         "
            +"			tab2.order_id,                                                                                             "
            +"			tab1.e_dt,                                                                                                 "
            +"			SUM( tab1.actual_count ) AS actual_count                                                                   "
            +"		FROM                                                                                                           "
            +"			b_out tab1                                                                                                 "
            +"			LEFT JOIN b_out_plan_detail tab2 ON tab2.id = tab1.plan_detail_id                                          "
            +"			LEFT JOIN b_out_plan tab3 ON tab3.id = tab2.plan_id                                                        "
            +"			LEFT JOIN m_warehouse tab4 ON tab4.id = tab1.warehouse_id                                                  "
            +"		WHERE                                                                                                          "
            +"		TRUE                                                                                                           "
            +"			AND tab3.type =  '"+DictConstant.DICT_B_OUT_PLAN_TYPE_JG+"'                                                "
            +"			AND tab2.STATUS =  '"+DictConstant.DICT_B_OUT_PLAN_STATUS_PASSED+"'                                        "
            +"			AND tab1.STATUS =  '"+DictConstant.DICT_B_OUT_STATUS_PASSED+"'                                             "
            +"			AND tab4.warehouse_type = '"+DictConstant.DICT_M_WAREHOUSE_TYPE_ZX+"'                                      "
            +"		GROUP BY                                                                                                       "
            +"			tab2.order_id                                                                                              "
            +"		ORDER BY                                                                                                       "
            +"			tab1.e_dt DESC                                                                                             "
            +"		) t5 ON t5.order_id = t2.id,(select @row_num:=0) t6                                                            "
            +"	WHERE                                                                                                              "
            +"	TRUE                                                                                                               "
            +"		AND t1.serial_type = '"+DictConstant.DICT_SYS_CODE_TYPE_B_IN_ORDER+"'                                          "
            +"		AND t3.order_id IS NOT NULL                                                                                    "
            +"		AND t1.contract_no LIKE '%G0%'                                                                                 "
            +" <if test='p1 != null and p1.export_codes!= null'>                                                                   "
            +"		AND CONCAT(substring( t1.contract_no, 6, 2 ), '-', substring( t1.contract_no, 8, 2 ),'-',                      "
            +"        substring( t1.contract_no, 10, 2 ),'-',t3.warehouse_id)  in                                                  "
            +"      <foreach collection='p1.export_codes' item='item' index='index' open='(' separator=',' close=')'>              "
            +"          #{item}                                                                                                    "
            +"      </foreach>                                                                                                     "
            +" </if>                                                                                                               "
            +"	GROUP BY                                                                                                           "
            +"		t3.warehouse_id,                                                                                               "
            +"		t1.contract_no ) AS tab WHERE TRUE                                                                                    "
            +"         AND (DATE_FORMAT(tab.opening_date,'%Y-%m-%d') &gt;= DATE_FORMAT(#{p1.opening_date_start},'%Y-%m-%d') or #{p1.opening_date_start} is null  or #{p1.opening_date_start} ='')                "
            +"         AND (DATE_FORMAT(tab.opening_date,'%Y-%m-%d') &lt;= DATE_FORMAT(#{p1.opening_date_end},'%Y-%m-%d') or #{p1.opening_date_end} is null or #{p1.opening_date_end} = '')                      "
            +"         AND ( tab.auction_date like CONCAT ('%',#{p1.auction_date,jdbcType=VARCHAR},'%') or #{p1.auction_date,jdbcType=VARCHAR} is null or #{p1.auction_date} = '')                            "
            +"         AND ( tab.actual_plan_out_days= #{p1.actual_plan_out_days,jdbcType=VARCHAR} or #{p1.actual_plan_out_days,jdbcType=VARCHAR} is null or #{p1.actual_plan_out_days,jdbcType=VARCHAR} ='') "
            +"         AND ( tab.plan_out_speed &gt;= #{p1.plan_out_speed,jdbcType=VARCHAR} or #{p1.plan_out_speed,jdbcType=VARCHAR} is null or #{p1.plan_out_speed,jdbcType=VARCHAR} = '')                        "
            +" </script> "
    )
    List<BOrderInvertedExportVo> queryRealInvertedExport(@Param("p1") BOrderInvertedVo param);


    /**
     * 快照倒排查询
     */
    @Select("SELECT                                                                                                                      "
            +"      CONCAT( t1.auction_date, '-', t1.warehouse_id ) AS export_code,                                                      "
            +"      t1.*                                                                                                                 "
            +"    FROM                                                                                                                   "
            +"     b_order_inverted t1                                                                                                   "
            +"   WHERE TRUE                                                                                                              "
            +"     AND (date_format( t1.backups_date, '%Y-%m-%d' ) = date_format(#{p1.date}, '%Y-%m-%d')  or  #{p1.date} is null or  #{p1.date} = '')                                                     "
            +"     AND (DATE_FORMAT(t1.opening_date,'%Y-%m-%d') >= DATE_FORMAT(#{p1.opening_date_start},'%Y-%m-%d') or #{p1.opening_date_start} is null or #{p1.opening_date_start} = '')                 "
            +"     AND (DATE_FORMAT(t1.opening_date,'%Y-%m-%d') <= DATE_FORMAT(#{p1.opening_date_end},'%Y-%m-%d') or #{p1.opening_date_end} is null or #{p1.opening_date_end} ='')                        "
            +"     AND (t1.auction_date like CONCAT ('%',#{p1.auction_date,jdbcType=VARCHAR},'%') or #{p1.auction_date,jdbcType=VARCHAR} is null or #{p1.auction_date,jdbcType=VARCHAR} ='')              "
            +"     AND ( t1.actual_plan_out_days= #{p1.actual_plan_out_days,jdbcType=VARCHAR} or #{p1.actual_plan_out_days,jdbcType=VARCHAR} is null or #{p1.actual_plan_out_days,jdbcType=VARCHAR} = '') "
            +"     AND ( t1.plan_out_speed >= #{p1.plan_out_speed,jdbcType=VARCHAR} or #{p1.plan_out_speed,jdbcType=VARCHAR} is null or #{p1.plan_out_speed,jdbcType=VARCHAR} = '')                         "
    )
    List<BOrderInvertedVo> querySnapshotInvertedOrder(Page pageCondition, @Param("p1")BOrderInvertedVo searchCondition);

    /**
     * 快照倒排导出
     */
    @Select("SELECT                                                                                                                      "
            +"      @row_num:= @row_num+ 1 as no,                                                                                        "
            +"      CONCAT( t1.auction_date, '-', t1.warehouse_id ) AS export_code,                                                      "
            +"      t1.*                                                                                                                 "
            +"    FROM                                                                                                                   "
            +"     b_order_inverted t1,(select @row_num:=0) t2                                                                           "
            +"    WHERE TRUE                                                                                                             "
            +"     AND (date_format( t1.backups_date, '%Y-%m-%d' ) = date_format(#{p1.date}, '%Y-%m-%d')  or  #{p1.date} is null or  #{p1.date} = '')                                                     "
            +"     AND (DATE_FORMAT(t1.opening_date,'%Y-%m-%d') >= DATE_FORMAT(#{p1.opening_date_start},'%Y-%m-%d') or #{p1.opening_date_start} is null or #{p1.opening_date_start} = '')                 "
            +"     AND (DATE_FORMAT(t1.opening_date,'%Y-%m-%d') <= DATE_FORMAT(#{p1.opening_date_end},'%Y-%m-%d') or #{p1.opening_date_end} is null or #{p1.opening_date_end} ='')                        "
            +"     AND (t1.auction_date like CONCAT ('%',#{p1.auction_date,jdbcType=VARCHAR},'%') or #{p1.auction_date,jdbcType=VARCHAR} is null or #{p1.auction_date,jdbcType=VARCHAR} ='')              "
            +"     AND ( t1.actual_plan_out_days= #{p1.actual_plan_out_days,jdbcType=VARCHAR} or #{p1.actual_plan_out_days,jdbcType=VARCHAR} is null or #{p1.actual_plan_out_days,jdbcType=VARCHAR} = '') "
            +"     AND ( t1.plan_out_speed >= #{p1.plan_out_speed,jdbcType=VARCHAR} or #{p1.plan_out_speed,jdbcType=VARCHAR} is null or #{p1.plan_out_speed,jdbcType=VARCHAR} = '')                         "
    )
    List<BOrderInvertedExportVo> querySnapshotInvertedExportAll(@Param("p1") BOrderInvertedVo param);

    /**
     * 快照倒排导出
     */
    @Select(" <script> "
            +"SELECT                                                                                                                       "
            +"      @row_num:= @row_num+ 1 as no,                                                                                         "
            +"      CONCAT( t1.auction_date, '-', t1.warehouse_id ) AS export_code,                                                       "
            +"      t1.*                                                                                                                  "
            +"    FROM                                                                                                                    "
            +"     b_order_inverted t1,(select @row_num:=0) t2                                                                            "
            +"    WHERE TRUE                                                                                                              "
            +" <if test='p1 != null and p1.export_codes!= null'>                                                                          "
            +"		AND CONCAT( t1.auction_date, '-', t1.warehouse_id )  in                                                               "
            +"      <foreach collection='p1.export_codes' item='item' index='index' open='(' separator=',' close=')'>                     "
            +"          #{item}                                                                                                           "
            +"      </foreach>                                                                                                            "
            +" </if>                                                                                                                      "
            +"     AND (date_format( t1.backups_date, '%Y-%m-%d' ) = date_format(#{p1.date}, '%Y-%m-%d')  or  #{p1.date} is null or  #{p1.date} = '')                                                     "
            +"     AND (DATE_FORMAT(t1.opening_date,'%Y-%m-%d') &gt;= DATE_FORMAT(#{p1.opening_date_start},'%Y-%m-%d') or #{p1.opening_date_start} is null or #{p1.opening_date_start} = '')              "
            +"     AND (DATE_FORMAT(t1.opening_date,'%Y-%m-%d') &lt;= DATE_FORMAT(#{p1.opening_date_end},'%Y-%m-%d') or #{p1.opening_date_end} is null or #{p1.opening_date_end} ='')                     "
            +"     AND (t1.auction_date like CONCAT ('%',#{p1.auction_date,jdbcType=VARCHAR},'%') or #{p1.auction_date,jdbcType=VARCHAR} is null or #{p1.auction_date,jdbcType=VARCHAR} ='')              "
            +"     AND ( t1.actual_plan_out_days= #{p1.actual_plan_out_days,jdbcType=VARCHAR} or #{p1.actual_plan_out_days,jdbcType=VARCHAR} is null or #{p1.actual_plan_out_days,jdbcType=VARCHAR} ='') "
            +"     AND ( t1.plan_out_speed &gt;= #{p1.plan_out_speed,jdbcType=VARCHAR} or #{p1.plan_out_speed,jdbcType=VARCHAR} is null or #{p1.plan_out_speed,jdbcType=VARCHAR} = '')                         "
            +" </script> "
    )
    List<BOrderInvertedExportVo> querySnapshotInvertedExport(@Param("p1") BOrderInvertedVo param);

    @Select("	SELECT                                                                                                             "
            +"		CONCAT(substring( t1.contract_no, 6, 2 ), '-', substring( t1.contract_no, 8, 2 ),'-',                          "
            +"        substring( t1.contract_no, 10, 2 )) AS auction_date                                                          "
            +"	FROM                                                                                                               "
            +"		b_order t1                                                                                                     "
            +"		LEFT JOIN b_in_order t2 ON t1.serial_id = t2.id                                                                "
            +"		AND t2.STATUS != '"+ DictConstant.DICT_B_IN_ORDER_STATUS_ONE+"'                                                 "
            +"		LEFT JOIN (                                                                                                    "
            +"		SELECT                                                                                                         "
            +"			tab2.order_id,                                                                                             "
            +"			tab4.id AS warehouse_id,                                                                                   "
            +"			tab4.NAME,                                                                                                 "
            +"			tab2.audit_dt,                                                                                             "
            +"			IFNULL( SUM( tab3.actual_count ), 0 ) AS actual_count                                                      "
            +"		FROM                                                                                                           "
            +"			b_in_plan tab1                                                                                             "
            +"			LEFT JOIN b_in_plan_detail tab2 ON tab2.plan_id = tab1.id                                                  "
            +"			LEFT JOIN b_in tab3 ON tab3.plan_detail_id = tab2.id                                                       "
            +"			LEFT JOIN m_warehouse tab4 ON tab4.id = tab2.warehouse_id                                                  "
            +"		WHERE                                                                                                          "
            +"		TRUE                                                                                                           "
            +"			AND tab1.type = '"+DictConstant.DICT_B_IN_PLAN_TYPE_CG+"'                                                  "
            +"			AND tab2.STATUS IN ('"+DictConstant.DICT_B_IN_PLAN_STATUS_TWO +"','"+DictConstant.DICT_B_IN_PLAN_STATUS_FIVE+"') "
            +"			AND tab3.STATUS = '"+DictConstant.DICT_B_IN_STATUS_TWO+"'                                               "
            +"			AND tab4.warehouse_type = '"+DictConstant.DICT_M_WAREHOUSE_TYPE_ZX+"'                                      "
            +"		GROUP BY                                                                                                       "
            +"			tab4.id,                                                                                                   "
            +"			tab2.order_id                                                                                              "
            +"		ORDER BY                                                                                                       "
            +"			tab2.audit_dt ASC                                                                                          "
            +"		) t3 ON t2.id = t3.order_id                                                                                    "
            +"		LEFT JOIN (                                                                                                    "
            +"		SELECT                                                                                                         "
            +"			SUM( tab4.actual_count ) AS actual_count,                                                                  "
            +"			tab4.warehouse_id,                                                                                         "
            +"			tab1.order_id                                                                                              "
            +"		FROM                                                                                                           "
            +"			b_schedule tab1                                                                                            "
            +"			LEFT JOIN b_monitor tab2 ON tab2.schedule_id = tab1.id                                                     "
            +"			LEFT JOIN b_monitor_out tab3 ON tab3.monitor_id = tab2.id                                                  "
            +"			LEFT JOIN b_out tab4 ON tab3.out_id = tab4.id                                                              "
            +"			LEFT JOIN m_warehouse tab5 ON tab5.id = tab4.warehouse_id                                                  "
            +"		WHERE                                                                                                          "
            +"		TRUE                                                                                                           "
            +"			AND tab5.warehouse_type = '"+DictConstant.DICT_M_WAREHOUSE_TYPE_ZX+"'                                      "
            +"			AND tab4.STATUS = '"+DictConstant.DICT_B_OUT_STATUS_PASSED+"'                                              "
            +"			AND tab2.STATUS IN ( '"+DictConstant.DICT_B_MONITOR_STATUS_THREE+"',                                       "
            +"                '"+DictConstant.DICT_B_MONITOR_STATUS_FOUR+"', '"+DictConstant.DICT_B_MONITOR_STATUS_FIVE+"',        "
            +"                '"+DictConstant.DICT_B_MONITOR_STATUS_SIX+"','"+DictConstant.DICT_B_MONITOR_STATUS_SEVEN+"' )        "
            +"		GROUP BY                                                                                                       "
            +"			tab5.id,                                                                                                   "
            +"			tab1.order_id                                                                                              "
            +"		) t4 ON t4.order_id = t1.id                                                                                    "
            +"		LEFT JOIN (                                                                                                    "
            +"		SELECT                                                                                                         "
            +"			tab2.order_id,                                                                                             "
            +"			tab1.e_dt,                                                                                                 "
            +"			SUM( tab1.actual_count ) AS actual_count                                                                   "
            +"		FROM                                                                                                           "
            +"			b_out tab1                                                                                                 "
            +"			LEFT JOIN b_out_plan_detail tab2 ON tab2.id = tab1.plan_detail_id                                          "
            +"			LEFT JOIN b_out_plan tab3 ON tab3.id = tab2.plan_id                                                        "
            +"			LEFT JOIN m_warehouse tab4 ON tab4.id = tab1.warehouse_id                                                  "
            +"		WHERE                                                                                                          "
            +"		TRUE                                                                                                           "
            +"			AND tab3.type =  '"+DictConstant.DICT_B_OUT_PLAN_TYPE_JG+"'                                                "
            +"			AND tab2.STATUS =  '"+DictConstant.DICT_B_OUT_PLAN_STATUS_PASSED+"'                                        "
            +"			AND tab1.STATUS =  '"+DictConstant.DICT_B_OUT_STATUS_PASSED+"'                                             "
            +"			AND tab4.warehouse_type = '"+DictConstant.DICT_M_WAREHOUSE_TYPE_ZX+"'                                      "
            +"		GROUP BY                                                                                                       "
            +"			tab2.order_id                                                                                              "
            +"		ORDER BY                                                                                                       "
            +"			tab1.e_dt DESC                                                                                             "
            +"		) t5 ON t5.order_id = t2.id                                                                                    "
            +"	WHERE                                                                                                              "
            +"	TRUE                                                                                                               "
            +"		AND t1.serial_type = '"+DictConstant.DICT_SYS_CODE_TYPE_B_IN_ORDER+"'                                          "
            +"		AND t3.order_id IS NOT NULL                                                                                    "
            +"		AND t1.contract_no LIKE '%G0%'                                                                                 "
            +"	GROUP BY                                                                                                           "
            +"		t3.warehouse_id,                                                                                               "
            +"		t1.contract_no                                                                                                 ")
    List<String> getAuctionDateList();
}
