# ClickHouse 配置文件
scm:
  clickhouse:
    # 是否启用ClickHouse
    enabled: true
    # ClickHouse服务器地址
    host: ${CLICKHOUSE_HOST:127.0.0.1}
    # ClickHouse服务器端口
    port: ${CLICKHOUSE_PORT:8123}
    # 数据库名称
    database: ${CLICKHOUSE_DATABASE:scm_clickhouse}
    # 用户名
    username: ${CLICKHOUSE_USERNAME:default}
    # 密码
    password: ${CLICKHOUSE_PASSWORD:}
    # 连接池配置
    pool:
      # 最大连接数
      max-active: 20
      # 最小空闲连接数
      min-idle: 5
      # 最大空闲连接数
      max-idle: 10
      # 获取连接超时时间（毫秒）
      max-wait: 30000
      # 连接空闲超时时间（毫秒）
      min-evictable-idle-time: 600000
      # 连接生存时间（毫秒）
      max-lifetime: 1800000
      # 连接泄露检测阈值（毫秒）
      leak-detection-threshold: 60000
    # 超时配置
    timeout:
      # 连接超时时间（毫秒）
      connection: 30000
      # 查询超时时间（毫秒）
      query: 60000
      # Socket超时时间（毫秒）
      socket: 60000
      # 最大执行时间（秒）
      max-execution-time: 300
    # 重试配置
    retry:
      # 最大重试次数
      max-attempts: 3
      # 重试间隔（毫秒）
      delay: 1000
      # 重试乘数
      multiplier: 2.0
    # 监控配置
    monitoring:
      # 是否启用健康检查
      health-check-enabled: true
      # 健康检查间隔（秒）
      health-check-interval: 30
      # 是否启用指标收集
      metrics-enabled: true

# Spring Boot 异步配置
spring:
  task:
    execution:
      pool:
        # 核心线程数
        core-size: 2
        # 最大线程数
        max-size: 8
        # 队列容量
        queue-capacity: 500
        # 线程名前缀
        thread-name-prefix: "clickhouse-async-"
        # 线程保活时间
        keep-alive: 60s

# 日志配置
logging:
  level:
    com.xinyirunscm.scm.clickhouse: INFO
    com.clickhouse: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
  health:
    clickhouse:
      enabled: true

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
      
scm:
  clickhouse:
    enabled: true
    host: 127.0.0.1
    port: 8123
    database: scm_clickhouse_dev
    username: default
    password: ""
    pool:
      max-active: 10
      min-idle: 2
      max-idle: 5
    timeout:
      connection: 10000
      query: 30000
    retry:
      max-attempts: 2
    monitoring:
      health-check-enabled: true
      health-check-interval: 60
      metrics-enabled: true

logging:
  level:
    com.xinyirunscm.scm.clickhouse: DEBUG
    com.xinyirunscm.scm.clickhouse.exception: DEBUG

---
# 测试环境配置
spring:
  config:
    activate:
      on-profile: test
      
scm:
  clickhouse:
    enabled: false
    host: test-clickhouse.example.com
    port: 8123
    database: scm_clickhouse_test
    username: test_user
    password: "${CLICKHOUSE_PASSWORD:test_password}"
    pool:
      max-active: 15
      min-idle: 3
      max-idle: 8
    timeout:
      connection: 15000
      query: 45000
    retry:
      max-attempts: 2
      delay: 1500
    monitoring:
      health-check-enabled: true
      health-check-interval: 45
      metrics-enabled: true

logging:
  level:
    com.xinyirunscm.scm.clickhouse: INFO
    com.xinyirunscm.scm.clickhouse.exception: WARN

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
      
scm:
  clickhouse:
    enabled: true
    host: ${CLICKHOUSE_HOST:prod-clickhouse.example.com}
    port: ${CLICKHOUSE_PORT:8123}
    database: ${CLICKHOUSE_DATABASE:scm_clickhouse_prod}
    username: ${CLICKHOUSE_USERNAME:prod_user}
    password: "${CLICKHOUSE_PASSWORD:prod_password}"
    pool:
      max-active: 50
      min-idle: 10
      max-idle: 25
      max-wait: 10000
      min-evictable-idle-time: 300000
      max-lifetime: 900000
      leak-detection-threshold: 30000
    timeout:
      connection: 10000
      query: 300000
      socket: 300000
      max-execution-time: 600
    retry:
      max-attempts: 3
      delay: 1000
      multiplier: 1.5
    monitoring:
      health-check-enabled: true
      health-check-interval: 30
      metrics-enabled: true

logging:
  level:
    com.xinyirunscm.scm.clickhouse: WARN
    com.xinyirunscm.scm.clickhouse.exception: ERROR