package com.xinyirun.scm.core.api.mapper.business.borroworder;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.xinyirun.scm.bean.entity.busniess.releaseorder.BReleaseOrderEntity;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

/**
 * @author Wang Qianfeng
 * @date 2022/11/30 16:32
 */
@Repository
public interface ApiBBorrowOrderMapper extends BaseMapper<BReleaseOrderEntity> {

    @Update("		update                                                                                             "
            + "			b_release_order t                                                                              "
            + "		inner join b_wk_release_order t1 on t.code = t1.code                                                  "
            + "			set                                                                                            "
            + "				t.code = t1.code,                                                                          "
            + "				t.type_name = t1.type_name,                                                                "
            + "				t.business_plate_name = t1.business_plate_name,                                            "
            + "				t.business_type_name = t1.business_type_name,                                              "
            + "				t.contract_code = t1.contract_code,                                                        "
            + "				t.order_code = t1.order_code,                                                              "
            + "				t.purchase_order_return_code = t1.purchase_order_return_code,                              "
            + "				t.customer_name = t1.customer_name,                                                        "
            + "				t.customer_code = t1.customer_code,                                                        "
            + "				t.consignor_name = t1.consignor_name,                                                      "
            + "				t.consignor_code = t1.consignor_code,                                                      "
            + "				t.owner_name = t1.owner_name,                                                              "
            + "				t.owner_code = t1.owner_code,                                                              "
            + "				t.direct_info = t1.direct_info,                                                            "
            + "				t.out_time = t1.out_time,                                                                  "
            + "				t.plan_time = t1.plan_time,                                                                "
            + "				t.float_controled = t1.float_controled,                                                    "
            + "				t.float_up = t1.float_up,                                                                  "
            + "				t.float_down = t1.float_down,                                                              "
            + "				t.total_amount = t1.total_amount,                                                          "
            + "				t.balance = t1.balance,                                                                    "
            + "				t.use_sealed = t1.use_sealed,                                                              "
            + "				t.status_name = t1.status_name,                                                            "
            + "				t.remark = t1.remark,                                                                      "
            + "				t.c_name = t1.c_name,                                                                      "
            + "				t.u_name = t1.u_name,                                                                      "
            + "				t.c_time = now(),                                                                          "
            + "				t.u_time = now()                                                                           "
            + "			where t1.code = t.code                                                                        ")
    void updateB_release_order30();

    @Insert("INSERT INTO                                                                                                "
            + " b_release_order                                                                                         "
            + " ( code,                                                                                                 "
            + " type_name,                                                                                              "
            + " order_type,                                                                                             "
            + " business_plate_name,                                                                                    "
            + " business_type_name,                                                                                     "
            + " contract_code,                                                                                          "
            + " order_code,                                                                                             "
            + " purchase_order_return_code,                                                                             "
            + " customer_name,                                                                                          "
            + " customer_code,                                                                                          "
            + " consignor_name,                                                                                         "
            + " consignor_code,                                                                                         "
            + " owner_name,                                                                                             "
            + " owner_code,                                                                                             "
            + " direct_info,                                                                                            "
            + " out_time,                                                                                               "
            + " plan_time,                                                                                              "
            + " float_controled,                                                                                        "
            + " float_up,                                                                                               "
            + " float_down,                                                                                             "
            + " total_amount,                                                                                           "
            + " balance,                                                                                                "
            + " use_sealed,                                                                                             "
            + " status_name,                                                                                            "
            + " remark,                                                                                                 "
            + " c_name,                                                                                                 "
            + " u_name,                                                                                                 "
            + " c_time ,                                                                                                "
            + " u_time)                                                                                                 "
            + " SELECT                                                                                                  "
            + " t.code,                                                                                                 "
            + " t.type_name,                                                                                            "
            + " 1,                                                                                                      "
            + " t.business_plate_name,                                                                                  "
            + " t.business_type_name,                                                                                   "
            + " t.contract_code,                                                                                        "
            + " t.order_code,                                                                                           "
            + " t.purchase_order_return_code,                                                                           "
            + " t.customer_name,                                                                                        "
            + " t.customer_code,                                                                                        "
            + " t.consignor_name,                                                                                       "
            + " t.consignor_code,                                                                                       "
            + " t.owner_name,                                                                                           "
            + " t.owner_code,                                                                                           "
            + " t.direct_info,                                                                                          "
            + " t.out_time,                                                                                             "
            + " t.plan_time,                                                                                            "
            + " t.float_controled,                                                                                      "
            + " t.float_up,                                                                                             "
            + " t.float_down,                                                                                           "
            + " t.total_amount,                                                                                         "
            + " t.balance,                                                                                              "
            + " t.use_sealed,                                                                                           "
            + " t.status_name,                                                                                          "
            + " t.remark,                                                                                               "
            + " t.c_name,                                                                                               "
            + " t.u_name,                                                                                               "
            + " now(),                                                                                                  "
            + " now()                                                                                                   "
            + " From b_wk_release_order t                                                                               "
            + " LEFT JOIN b_release_order t1 ON t.code = t1.code                                                        "
            + " where t1.id is null                                                                                     "
    )
    void insertB_release_order30();
}
