package com.xinyirun.scm.core.system.mapper.business.rpd;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.xinyirun.scm.bean.entity.busniess.rpd.RProductDailyCEntity;
import com.xinyirun.scm.bean.system.vo.business.rpd.BProductDailyVo;
import com.xinyirun.scm.common.constant.DictConstant;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

/**
 * <p>
 * 玉米 加工日报表 Mapper 接口
 * </p>
 *
 * @author xinyirun
 * @since 2023-05-16
 */
@Repository
public interface RProductDailyCMapper extends BaseMapper<RProductDailyCEntity> {

    @Delete(""
            + " DELETE FROM                                                                                             "
            + "   r_product_daily_c                                                                                     "
            + " WHERE date_format(date, '%Y%m%d') = date_format(#{p1.date}, '%Y%m%d')                                        "
//            + " AND (date_format(date, '%Y-%m-%d') >= #{p1.start_time} or #{p1.start_time} is null)                     "
//            + " AND (date_format(date, '%Y-%m-%d') <= #{p1.end_time} or #{p1.end_time} is null)                         "
    )
    void deleteR_product_daily_c_41(@Param("p1") BProductDailyVo vo);

    @Insert(""
            + "   INSERT INTO r_product_daily_c ( date, warehouse_id, in_qty, cost_qty, inventory_qty, router, c_time ) SELECT"
            + "   tab1.date,                                                                                            "
            + "   tab1.warehouse_id,                                                                                    "
            + "   tab2.in_qty,                                                                                          "
            + "   tab3.cost_qty,                                                                                        "
            + "   tab5.inventory_qty,                                                                                   "
            + "   tab4.wo_router,                                                                                       "
            + "   now()                                                                                                 "
            + "   FROM                                                                                                  "
            + "   	(                                                                                                   "
            + "   	SELECT                                                                                              "
            + "   		t.id warehouse_id,                                                                              "
            + "   		t1.date                                                                                         "
            + "   	FROM                                                                                                "
            + "   		m_warehouse t,                                                                                  "
            + "   		s_calendar t1                                                                                   "
            + "   	WHERE                                                                                               "
            + "         date_format(date, '%Y%m%d') = date_format(#{p1.date}, '%Y%m%d')                                      "
//            + "  		AND (date_format(date, '%Y-%m-%d') >= #{p1.start_time} or #{p1.start_time} is null)             "
//            + "  		AND (date_format(date, '%Y-%m-%d') <= #{p1.end_time} or #{p1.end_time} is null)                 "
            + "  		AND t.warehouse_type = '"+ DictConstant.DICT_M_WAREHOUSE_TYPE_WD +"'                            "
            + "  		AND t.`enable` = '1'                                                                            "
            + "   	) tab1                                                                                              "
            + "   	LEFT JOIN (                                                                                         "
            + "   	SELECT                                                                                              "
            + "   		SUM( t.actual_weight ) in_qty,                                                                   "
            + "   		DATE_FORMAT( t.e_dt, '%Y-%m-%d' ) date,                                                         "
            + "   		t.warehouse_id                                                                                  "
            + "   	FROM                                                                                                "
            + "   		b_in t                                                                                          "
            + "   		LEFT JOIN m_goods_spec t1 ON t.sku_id = t1.id                                                   "
            + "   		LEFT JOIN m_warehouse t2 ON t.warehouse_id = t2.id                                              "
            + "   	WHERE                                                                                               "
            + "   		t.type in( '"+ DictConstant.DICT_B_IN_TYPE_CG +"', '"+ DictConstant.DICT_B_IN_TYPE_JG +"')      "
            + "   		AND t.`status` = '2'                                                                            "
            + "   		AND t1.goods_code = #{p1.p00000128Vo.column_three}                                                          "
            +  "  		AND t2.warehouse_type = '"+ DictConstant.DICT_M_WAREHOUSE_TYPE_WD +"'                           "
            + "   		AND t2.`enable` = '1'                                                                           "
            + "   	GROUP BY                                                                                            "
            + "   		t.warehouse_id,                                                                                 "
            + "   		DATE_FORMAT( t.e_dt, '%Y%m%d' )                                                                 "
            + "   	) tab2 ON tab1.warehouse_id = tab2.warehouse_id                                                     "
            + "   	AND tab1.date = tab2.date                                                                           "
            + "   	LEFT JOIN (                                                                                         "
            + "   	SELECT                                                                                              "
            + "   		SUM( t.actual_weight ) cost_qty,                                                                 "
            + "   		DATE_FORMAT( t.e_dt, '%Y-%m-%d' ) date,                                                         "
            + "   		t.warehouse_id                                                                                  "
            + "   	FROM                                                                                                "
            + "   		b_out t                                                                                         "
            + "   		LEFT JOIN m_goods_spec t1 ON t.sku_id = t1.id                                                   "
            + "   		LEFT JOIN m_warehouse t2 ON t.warehouse_id = t2.id                                              "
            + "   	WHERE                                                                                               "
            + "   		t.type = '"+ DictConstant.DICT_B_OUT_TYPE_LL +"'                                                "
            + "   		AND t.`status` = '2'                                                                            "
            + "   		AND t1.goods_code = #{p1.p00000128Vo.column_three}                                              "
            +  "  		AND t2.warehouse_type = '"+ DictConstant.DICT_M_WAREHOUSE_TYPE_WD +"'                           "
            + "   		AND t2.`enable` = '1'                                                                           "
            + "   	GROUP BY                                                                                            "
            + "   		t.warehouse_id,                                                                                 "
            + "   		DATE_FORMAT( t.e_dt, '%Y%m%d' )                                                                 "
            + "   	) tab3 ON tab1.warehouse_id = tab3.warehouse_id                                                     "
            + "   	AND tab1.date = tab3.date                                                                           "
            + "   	LEFT JOIN (                                                                                         "
            + "   	SELECT                                                                                              "
            + "   		SUM( t.qty_avaible ) inventory_qty,                                                             "
            + "   		t.warehouse_id                                                                                  "
            + "   	FROM                                                                                                "
            + "   		m_inventory t                                                                                   "
            + "   		LEFT JOIN m_goods_spec t1 ON t.sku_id = t1.id                                                   "
            + "   		LEFT JOIN m_warehouse t2 ON t.warehouse_id = t2.id                                              "
            + "   	WHERE                                                                                               "
            + "  		t2.warehouse_type = '"+ DictConstant.DICT_M_WAREHOUSE_TYPE_WD +"'                               "
            + "   		AND t2.`enable` = '1'                                                                           "
            + "   		AND t1.goods_code = #{p1.p00000128Vo.column_three}                                              "
            + "   	GROUP BY                                                                                            "
            + "   	t.warehouse_id                                                                                      "
            + "   	) tab5 ON tab1.warehouse_id = tab5.warehouse_id                                                     "
            + "   	LEFT JOIN                                                                                           "
            + "   	(                                                                                                   "
            + "      SELECT                                                                                             "
            + "   	   t.wo_router,                                                                                     "
            + "   		 t.warehouse_id                                                                                 "
            + "   	 FROM                                                                                               "
            + "   	   b_wo_material t                                                                                  "
            + "   	 LEFT JOIN m_goods_spec t1 ON t.sku_id = t1.id                                                      "
            + "   	 LEFT JOIN m_warehouse t2 ON t.warehouse_id = t2.id                                                 "
            + "   	 LEFT JOIN b_wo t3 ON t.wo_id = t3.id                                                               "
            + "   	 WHERE                                                                                              "
            + "      t2.warehouse_type = '"+ DictConstant.DICT_M_WAREHOUSE_TYPE_WD +"'                                  "
            + "   	 AND t2.`enable` = '1'                                                                              "
            + "   	 AND t1.goods_code = #{p1.p00000128Vo.column_three}                                                 "
            + "   	 AND t3.`status` = '3'                                                                              "
            + " AND EXISTS (SELECT 1 FROM b_in sub_t LEFT JOIN m_goods_spec sub_t1 ON sub_t.sku_id = sub_t1.id WHERE sub_t1.goods_code IN ('zlsd-0100510', '19') AND  sub_t.e_dt_date = DATE_FORMAT( NOW(), '%Y-%m-%d' ))"
            + "   	 ORDER BY t3.c_time DESC                                                                            "
            + "   	 limit 1                                                                                            "
            + "   	) tab4 ON tab1.warehouse_id = tab4.warehouse_id                                                     "
            + "  WHERE                                                                                                  "
//            +  "   (tab2.in_qty is not null or tab3.cost_qty is not null or tab4.wo_router is not null or tab5.inventory_qty is not null)"
            +  "   (ifnull(tab2.in_qty, 0) != 0 or ifnull(tab3.cost_qty, 0) != 0  or ifnull(tab5.inventory_qty, 0) != 0)"
    )
    void insertR_product_daily_c_42(@Param("p1") BProductDailyVo vo);

    @Delete(""
            + " DELETE FROM                                                                                             "
            + "   r_product_daily_c                                                                                     "
            + " WHERE TRUE                                                                                              "
            + " AND (date_format(date, '%Y-%m-%d') >= #{p1.init_time} or #{p1.init_time} is null or #{p1.init_time} = '')"
            + " AND (date_format(date, '%Y-%m-%d') <= #{p1.end_time} or #{p1.end_time} is null or #{p1.end_time} = '' ) "
            + " AND (warehouse_id = #{p1.warehouse_id} or #{p1.warehouse_id} is null or #{p1.warehouse_id} = '')        "
    )
    void deleteR_product_daily_c_401(@Param("p1") BProductDailyVo vo);

    @Insert(""
            + "   INSERT INTO r_product_daily_c ( date, warehouse_id, in_qty, cost_qty, inventory_qty, router, c_time ) SELECT"
            + "   tab1.date,                                                                                            "
            + "   tab1.warehouse_id,                                                                                    "
            + "   tab2.in_qty,                                                                                          "
            + "   tab3.cost_qty,                                                                                        "
            + "   tab5.inventory_qty,                                                                                   "
            + "   tab4.wo_router,                                                                                       "
            + "   now()                                                                                                 "
            + "   FROM                                                                                                  "
            + "   	(                                                                                                   "
            + "   	SELECT                                                                                              "
            + "   		t.id warehouse_id,                                                                              "
            + "   		t1.date                                                                                         "
            + "   	FROM                                                                                                "
            + "   		m_warehouse t,                                                                                  "
            + "   		s_calendar t1                                                                                   "
            +  "  	WHERE TRUE                                                                                          "
//            +  "        date_format(date, '%Y%m%d') = date_format(p1.date, '%Y%m%d')                                      "
            +  "  		AND (date_format(date, '%Y-%m-%d') >= #{p1.init_time} or #{p1.init_time} is null)               "
            +  "  		AND (date_format(date, '%Y-%m-%d') <= #{p1.end_time} or #{p1.end_time} is null)                 "
            +  "        AND (t.id = #{p1.warehouse_id} or #{p1.warehouse_id} is null or #{p1.warehouse_id} = '')        "
            + "  		AND t.warehouse_type = '"+ DictConstant.DICT_M_WAREHOUSE_TYPE_WD +"'                            "
            + "  		AND t.`enable` = '1'                                                                            "
            + "   	) tab1                                                                                              "
            + "   	LEFT JOIN (                                                                                         "
            + "   	SELECT                                                                                              "
            + "   		SUM( t.actual_weight ) in_qty,                                                                   "
            + "   		DATE_FORMAT( t.e_dt, '%Y-%m-%d' ) date,                                                         "
            + "   		t.warehouse_id                                                                                  "
            + "   	FROM                                                                                                "
            + "   		b_in t                                                                                          "
            + "   		LEFT JOIN m_goods_spec t1 ON t.sku_id = t1.id                                                   "
            + "   		LEFT JOIN m_warehouse t2 ON t.warehouse_id = t2.id                                              "
            + "   	WHERE                                                                                               "
            + "   		t.type in( '"+ DictConstant.DICT_B_IN_TYPE_CG +"', '"+ DictConstant.DICT_B_IN_TYPE_JG +"')      "
            + "   		AND t.`status` = '2'                                                                            "
            + "   		AND t1.goods_code = #{p1.p00000128Vo.column_three}                                                          "
            +  "  		AND t2.warehouse_type = '"+ DictConstant.DICT_M_WAREHOUSE_TYPE_WD +"'                           "
            + "   		AND t2.`enable` = '1'                                                                           "
            + "   	GROUP BY                                                                                            "
            + "   		t.warehouse_id,                                                                                 "
            + "   		DATE_FORMAT( t.e_dt, '%Y%m%d' )                                                                 "
            + "   	) tab2 ON tab1.warehouse_id = tab2.warehouse_id                                                     "
            + "   	AND tab1.date = tab2.date                                                                           "
            + "   	LEFT JOIN (                                                                                         "
            + "   	SELECT                                                                                              "
            + "   		SUM( t.actual_weight ) cost_qty,                                                                 "
            + "   		DATE_FORMAT( t.e_dt, '%Y-%m-%d' ) date,                                                         "
            + "   		t.warehouse_id                                                                                  "
            + "   	FROM                                                                                                "
            + "   		b_out t                                                                                         "
            + "   		LEFT JOIN m_goods_spec t1 ON t.sku_id = t1.id                                                   "
            + "   		LEFT JOIN m_warehouse t2 ON t.warehouse_id = t2.id                                              "
            + "   	WHERE                                                                                               "
            + "   		t.type = '"+ DictConstant.DICT_B_OUT_TYPE_LL +"'                                                "
            + "   		AND t.`status` = '2'                                                                            "
            + "   		AND t1.goods_code = #{p1.p00000128Vo.column_three}                                                          "
            +  "  		AND t2.warehouse_type = '"+ DictConstant.DICT_M_WAREHOUSE_TYPE_WD +"'                           "
            + "   		AND t2.`enable` = '1'                                                                           "
            + "   	GROUP BY                                                                                            "
            + "   		t.warehouse_id,                                                                                 "
            + "   		DATE_FORMAT( t.e_dt, '%Y%m%d' )                                                                 "
            + "   	) tab3 ON tab1.warehouse_id = tab3.warehouse_id                                                     "
            + "   	AND tab1.date = tab3.date                                                                           "
            + "   	LEFT JOIN (                                                                                         "
            + "   	SELECT                                                                                              "
            + "   		SUM(t.qty) inventory_qty,                                                                       "
            + "        DATE_FORMAT(t.dt,'%Y-%m-%d') dt,                                                                   "
            + "   		t.warehouse_id                                                                                  "
            + "   	FROM                                                                                                "
            + "   		b_daily_inventory t                                                                             "
            + "   		LEFT JOIN m_goods_spec t1 ON t.sku_id = t1.id                                                   "
            + "   		LEFT JOIN m_warehouse t2 ON t.warehouse_id = t2.id                                              "
            + "   	WHERE                                                                                               "
            + "  		t2.warehouse_type = '"+ DictConstant.DICT_M_WAREHOUSE_TYPE_WD +"'                               "
            + "   		AND t2.`enable` = '1'                                                                           "
            + "   		AND t1.goods_code = #{p1.p00000128Vo.column_three}                                              "
            + "   	GROUP BY                                                                                            "
            + "   	t.warehouse_id,                                                                                     "
            +  "    DATE_FORMAT(t.dt,'%Y%m%d')                                                                          "
            + "   	) tab5 ON tab1.warehouse_id = tab5.warehouse_id  AND  tab5.dt = tab1.date                           "
            + "   	LEFT JOIN                                                                                           "
            + "   	(                                                                                                   "
            + "      SELECT                                                                                             "
            + "   	   t.wo_router,                                                                                     "
            + "   		 t.warehouse_id                                                                                 "
            + "   	 FROM                                                                                               "
            + "   	   b_wo_material t                                                                                  "
            + "   	 LEFT JOIN m_goods_spec t1 ON t.sku_id = t1.id                                                      "
            + "   	 LEFT JOIN m_warehouse t2 ON t.warehouse_id = t2.id                                                 "
            + "   	 LEFT JOIN b_wo t3 ON t.wo_id = t3.id                                                               "
            + "   	 WHERE                                                                                              "
            + "      t2.warehouse_type = '"+ DictConstant.DICT_M_WAREHOUSE_TYPE_WD +"'                                  "
            + "   	 AND t2.`enable` = '1'                                                                              "
            + "   	 AND t1.goods_code = #{p1.p00000128Vo.column_three}                                                             "
            + "   	 AND t3.`status` = '3'                                                                              "
            + " AND EXISTS (SELECT 1 FROM b_in sub_t LEFT JOIN m_goods_spec sub_t1 ON sub_t.sku_id = sub_t1.id WHERE sub_t1.goods_code IN ('zlsd-0100510', '19') AND  sub_t.e_dt_date = DATE_FORMAT( NOW(), '%Y-%m-%d' ))"
            + "   	 ORDER BY t3.c_time DESC                                                                            "
            + "   	 limit 1                                                                                            "
            + "   	) tab4 ON tab1.warehouse_id = tab4.warehouse_id                                                     "
            + "  WHERE                                                                                                  "
//            +  "   (tab2.in_qty is not null or tab3.cost_qty is not null or tab4.wo_router is not null or tab5.inventory_qty is not null)"
            +  "   (ifnull(tab2.in_qty, 0) != 0 or ifnull(tab3.cost_qty, 0) != 0 or ifnull(tab5.inventory_qty, 0) != 0) "
    )
    void insertR_product_daily_c_402(@Param("p1") BProductDailyVo vo);
}
